name = "list_image"
description = "helper to dump iterable containers with customizable style"
version = "2.0.0-dev"

authors = ["Lionel Draghi"]
maintainers = ["Lionel Draghi <lionel.draghi@free.fr>"]
maintainers-logins = ["LionelDraghi"]
licenses = "Apache-2.0"
website = "https://github.com/LionelDraghi/List_Image"
tags = ["list", "iterator", "container", "markdown", "html"]

executables = ["test_list_image"]

[configuration]
disabled = true

